### ISSUE TITLE
Game freezes on drought end

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#1]
When a drought ends, the game freezes with a console error.

Uncaught TypeError: Cannot read properties of undefined (reading 'trait')
    at G.deleteTrait (magixUtils.js?r=0.8384687040668799:1926:53)
    at G.funcs.new year (magix.js?r=0.49900023508299995:1681:35)
    at G.doFunc (main.js?v=13b:2232:42)
    at G.Logic (magixUtils.js?r=0.8384687040668799:4670:67)
    at G.Loop (main.js?v=13b:8207:5)

Line 1926 of magixUtils.js:
            G.applyKnowEffects(G.traitsOwned[index].trait, true, true);

It almost seems like the game is trying to delete a trait that doesn't exist. There should probably be some protection against this, as this causes an entire savegame to be unusable. The error is very much reproducible after a refresh.

**Comment by JanMiddelkoop** [comment]
It might be related to the Drought Preparation (?) trait, or something. After the reload I got a certain trait and the "Careful water storage" research available.

**Comment by plasma4** [comment]
Maybe there's a problem with traits somehow expiring or something; you should gain the "drought" trait whenever there is one active. Drought preparation is just a trait that you might gain with that trait active, so I'm not sure why that is occuring. Maybe that function is running at the wrong time or the object data is being messed up...I'll see what is happening.

**Comment by plasma4** [comment]
Update: I figured out the issue! Apparently, the `G.deleteTrait` function does not require you to get use `G.traitByName` first, so when I used it, deleting the trait would fail and would also end up throwing an error.
