### ISSUE TITLE
Black screen on game start (console error)

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#3]
Hi. When I start a new game after a save wipe, or in incognito mode, I get a black screen and cannot do anything meaningful.

Steps to reproduce:
Click 'Use mods', replace data.js with
https://file.garden/ZmatEHzFI2_QBuAF/magixUtils.js
https://file.garden/ZmatEHzFI2_QBuAF/magix.js
Click 'Pleasant' to start

Console errors:
Uncaught TypeError: G.res[i].tick is not a function
    at G.NewGameConfirm (main.js?v=13b:1363:13)
    at HTMLDivElement.onclick (main.js?v=13b:1314:296)

Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at G.Logic (magixUtils.js?r=0.9685590925308671:4673:49)
    at G.Loop (main.js?v=13b:8207:5)

**Comment by plasma4** [comment]
Ok, thanks for telling me. I'm fairly certain why this is happening, so give me a bit.

**Comment by plasma4** [comment]
I think I should have fixed it: just reload and try to do it again. I think what happened is that for the non-file version, I forgot to update the `NewGameConfirm` to test if the `tick` function existed in some resources.

**Comment by JanMiddelkoop** [comment]
I can confirm this is fixed, thanks! :-)
