### ISSUE TITLE
Cannot start building of Complex of Dreamers

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#5]
Hi Leo,

When trying to start building a Complex of Dreamers, I get the following (non-fatal) error:

No resource exists with the name Wizard Complex. main.js?v=13b:300

console.trace
ERROR @ main.js?v=13b:300
G.getRes @ main.js?v=13b:2596
G.testUse @ main.js?v=13b:2772
G.buyUnit @ magixUtils.js?r=0.615015958825688:5290
G.taskBuyUnit @ main.js?v=13b:3734
(anoniem) @ magixUtils.js?r=0.615015958825688:1065
main.js?v=13b:2773

Uncaught TypeError: Cannot read properties of undefined (reading 'amount')
    at G.testUse (main.js?v=13b:2773:19)
    at G.buyUnit (magixUtils.js?r=0.615015958825688:5290:33)
    at G.taskBuyUnit (main.js?v=13b:3734:25)
    at HTMLDivElement.<anonymous> (magixUtils.js?r=0.615015958825688:1065:56)
G.testUse @ main.js?v=13b:2773
G.buyUnit @ magixUtils.js?r=0.615015958825688:5290
G.taskBuyUnit @ main.js?v=13b:3734
(anoniem) @ magixUtils.js?r=0.615015958825688:1065

I could provide my save file if that helps.

**Comment by plasma4** [comment]
Thank you for telling me! I figured out why; apparently that item was a unit, which would break the game because that's not allowed for constructing things.
