### ISSUE TITLE
Syntax error in latest release

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#6]
Hi, You're missing an ) in your latest revisions. :-)

Uncaught SyntaxError: Unexpected token ';' (at magixUtils.js?r=0.8013134988641102:1719:139)
magix.js?r=0.5794757962646051:1142

Uncaught ReferenceError: getObj is not defined
    at magix.js?r=0.5794757962646051:1142:1

**Comment by plasma4** [comment]
Should be fixed now...sorry about that. I didn't upload the file to file.garden for a bit, so that might be why.
