### ISSUE TITLE
Logic error disables gaining of Faith II after 'People of the arts'

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#8]
Line 5922 of magix.js has a logic error. There is an upgrade for culture conversion, 'People of the arts', but this accidentally disables Faith II.

Lines 5921 and 5922 should be:

```
{ type: 'convert', from: { 'culture': 550 }, into: { 'culture II': 1.2 }, every: 9, mode: 'culture', req: { 'smartness of essentials': true, 'people of the arts II': false } },
{ type: 'convert', from: { 'faith': 550 }, into: { 'faith II': 1.2 }, every: 9, mode: 'faith', req: { 'smartness of essentials': true } },
```

Currently it's the wrong way around.

**Comment by plasma4** [comment]
Interesting...looking into it.

**Comment by plasma4** [comment]
Should be fixed now!

**Comment by JanMiddelkoop** [comment]
Thanks! Did you upload the changes to filegarden as well? :-)

**Comment by JanMiddelkoop** [comment]
Hi Leo. Any chance you can upload this to file.garden?
